### ISSUE TITLE
Cant use SimpleTCP with Windows Form

### ISSUE THREAD

**Issue by thipages** [BrandonPotter/SimpleTCP#1]
Hi,
I tried to write a simple application using Windows Form (VS2015)
I got a TypeLoadSystem exception. Find below the complete message (in French)
Can you help?
Thnak you

Une exception non gérée du type 'System.TypeLoadException' s'est produite dans System.Windows.Forms.dll
Informations supplémentaires : Impossible de charger le type 'SimpleTCP.SimpleTcpServer' à partir de l'assembly 'SimpleTCP, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

**Comment by BrandonPotter** [comment]
Any more details?

Sent from my iPhone

On Feb 22, 2016, at 4:22 AM, tit <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi,
I tried to write a simple application using Windows Form.

##

**Comment by thipages** [comment]
Hi,

I updated git

Hi,
I tried to write a simple application using Windows Form (VS2015)
I got a TypeLoadSystem exception. Find below the complete message (in
French)
Can you help?
Thnak you

Une exception non gérée du type 'System.TypeLoadException' s'est produite
dans System.Windows.Forms.dll
Informations supplémentaires : Impossible de charger le type
'SimpleTCP.SimpleTcpServer' à partir de l'assembly 'SimpleTCP,
Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

Thierry
Le 22 févr. 2016 5:07 PM, "Brandon Potter" notifications@github.com a
écrit :

> Any more details?
> 
> Sent from my iPhone
> 
> On Feb 22, 2016, at 4:22 AM, tit <notifications@github.com<mailto:

**Comment by BrandonPotter** [comment]
What version of .NET are you compiling against?

**Comment by thipages** [comment]
Hi
.net framework 4.5.2
Thierry
Le 23 févr. 2016 4:52 PM, "Brandon Potter" notifications@github.com a
écrit :

> What version of .NET are you compiling against?
> 
> From: tit [mailto:notifications@github.com]
> Sent: Monday, February 22, 2016 11:44 AM
> To: BrandonPotter/SimpleTCP SimpleTCP@noreply.github.com
> Cc: Brandon Potter bpotter@x9tech.com
> Subject: Re: [SimpleTCP] Cant use SimpleTCP with Windows Form (#1)
> 
> Hi,
> 
> I updated git
> 
> Hi,
> I tried to write a simple application using Windows Form (VS2015)
> I got a TypeLoadSystem exception. Find below the complete message (in
> French)
> Can you help?
> Thnak you
> 
> Une exception non gérée du type 'System.TypeLoadException' s'est produite
> dans System.Windows.Forms.dll
> Informations supplémentaires : Impossible de charger le type
> 'SimpleTCP.SimpleTcpServer' à partir de l'assembly 'SimpleTCP,
> Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
> 
> Thierry
> Le 22 févr. 2016 5:07 PM, "Brandon Potter" <notifications@github.com
> <mailto:notifications@github.com>> a
> écrit :
> 
> > Any more details?
> > 
> > Sent from my iPhone
> > 
> > On Feb 22, 2016, at 4:22 AM, tit <notifications@github.com<mailto:
> > <mailto:notifications@github.com%3cmailto:%0b>> notifications@github.com

**Comment by marcrupprath** [comment]
Hello,
besides the fact that this issue is quite old ;-)
i had a very similar error and solved it like this:
https://github.com/BrandonPotter/SimpleTCP/issues/60

Short: Not to use compiled.dll, integrate source files in your project.
Hope that helps.

Marc

**Comment by thipages** [comment]
thanks
