### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by holzbrenner** [BrandonPotter/SimpleTCP#20]
This project has no license, so theoretically / strictly legally nobody is allowed to use it, except to study the code and fork it here on github (but then you can't do anything with the fork). Even contributors can't use the library since they all share exclusive copyright for the code and should always ask permission from all other contributors before using the code in any way.

More details: [https://choosealicense.com/no-license/](https://choosealicense.com/no-license/)

If not for "real" production use, the library is still quite useful for prototyping, unit testing and stuff like that, but in my company I wouldn't be allowed to use it even for this (due to strict regulatory requirements in my specific branch - medical software development - every library has to be checked and validated before it can be used and this includes the license).

**Comment by BrandonPotter** [comment]
Not intentional, fixed.
