### ISSUE TITLE
Server send message to client

### ISSUE THREAD

**Issue by Xinnony** [BrandonPotter/SimpleTCP#56]
Hi, how the server can send a message to a specific client ?
I can use Broadcast but is not good.

Do you have a solution ?

**Comment by Xinnony** [comment]
Finally i use another Framework [https://github.com/hikalkan/scs](https://github.com/hikalkan/scs)

**Comment by twhalen08** [comment]
I am trying to figure this one out myself. I believe this is possible by adding another method to SimpleTCPServer.CS similar to... 


`        public void Broadcast(byte[] data)
        {
            foreach(var client in _listeners.SelectMany(x => x.ConnectedClients))
            {
                client.GetStream().Write(data, 0, data.Length);
            }
        }`

but I am getting hung up on the lambda expression. Any chance anyone can help me out? I believe i could have a method like this that also takes in an IP address and port and then in the lambda area there, I would think you could select only the specific client from the dictionary that you want and send a message to that specific client. 

Any help here would be super appreciated.
