### ISSUE TITLE
Simpletcp.dll requirements and dependencies --> Missing file or other libray

### ISSUE THREAD

**Issue by marcrupprath** [BrandonPotter/SimpleTCP#60]

**Comment by marcrupprath** [comment]
I have cretaed a demo applikation using Visual Studio 2017, where i have intsalled the package from the package manager.

After that i used your SimpleTCP.dll, within our Testbed application (it supports C# script ) on same computer and it is working fine. I copied the application (our orn system) so another computer where Simple TCP was not usd before. The only library present here is .net Framework 4.5 and your Simpletcp. dll

I can compile the script here two, but wehn i try to use and connect i git the following error message "File or assembly of simple.dll or one of its dependencies not found"

Problem is that we need your library urgently on an AUtomotive Testbed computer

Question:

In case visual studio is not present on the target machine, what are the exacl pre requirements on using simple.tcp on this machine.

How to install nuget packet here ?

Note: Unfortunately i only have error message screen in German language, see atachment

Thanks in advance
![Unbenannt](https://user-images.githubusercontent.com/6498534/62284067-33737280-b453-11e9-8512-c8edc4ac80c5.JPG)

**Comment by BrandonPotter** [comment]
Have you tried just bringing the code into your existing project? It’s only a few files..

**Comment by marcrupprath** [comment]
Hello, bringing code in existing project is not an option because they are two different systems.

"System one" is full featured Visual Studio
"System ti" is our automation System "Morphee" with a very basic c# script editor.
In "System two" we only have the option to set references to specific dll.

Emaging the follwoing:
How to use your Simple TCP . dll on a System where you can't manage nuget pakages, becaue you don't have Visual studio there.

What are a complete references of additional libraries that are neeeded to make the simpletcp.dll work ?
Short form:What are its dependencies on other dll
Which .net Framework is needed minimum.


And a list time:
It seams that a link to simpletcp.dll it not enough at all ?!



Thanks again

**Comment by marcrupprath** [comment]
Hello,
due to the limited resources for  c# script  development within our automation system
i solved it like this:
I have integrated the source code of the message and SimpleClientClass i need, in my application
on top of my sourcecode file and re-compile.
It works

**Comment by marcrupprath** [comment]
Solved as described above ;-)
