### ISSUE TITLE
strong-name related error

### ISSUE THREAD

**Issue by HeisenbergK** [BrandonPotter/SimpleTCP#61]
Hello,

I have used SimpleTCP in my code. When I am trying to implement it, I get the following error:

Could not load file or assembly 'SimpleTCP, Version=1.0.24.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)

**Comment by HeisenbergK** [comment]
The following procedure helped me:

Step 0: Install the library through NuGet
Step 1 : Run visual studio command prompt and go to directory where the DLL is located.
Step 2 : Create il file using:
```ildasm /all /out=Test.il Test.dll```
Step 3 : Generate new Key:
```sn -k mykey.snk```
Step 4 : Sign the library:
```ilasm /dll /key=mykey.snk Test.il```

After that the issue is resolved

**Comment by shahkamranqader** [comment]
@HeisenbergK 
I follow your complete procedure but issue not resolve yet. same problem.
Could not load file or assembly 'SimpleTCP, Version=1.0.24.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)

Step 0: Install the library through NuGet
Step 1 : Run visual studio command prompt and go to directory where the DLL is located.
Step 2 : Create il file using:
ildasm /all /out=Test.il SimpleTCP.dll
Step 3 : Generate new Key:
sn -k mykey.snk
Step 4 : Sign the library:
ilasm /dll /key=mykey.snk Test.il

**Comment by shahkamranqader** [comment]
System.IO.FileLoadException
  HResult=0x80131044
  Message=Could not load file or assembly 'SimpleTCP, Version=1.0.24.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
  Source=testproject
