### ISSUE TITLE
TcpClient in Message Class

### ISSUE THREAD

**Issue by nastymorbol** [BrandonPotter/SimpleTCP#9]
Hi,

i need access to the TcpClient in the DataReceived event. Is ist possible to add a public member to the Message Class?

**Comment by BrandonPotter** [comment]
Hmm, probably - What is the scenario you have?

**Comment by nastymorbol** [comment]
Hi,

I have to close the Client socket After Receive of a new Message. I Could make a Stack but it is more readable when i make this in the Event. 

Ive Forked your Project, Tested it and it Works like a sharm. 

Best thanks! And sorry for my Bad english ...

Von meinem iPhone gesendet

**Comment by WopsVSV** [comment]
I've got the same problem, really need to access the TcpClient in the DataReceived event. Can't figure out a way to do it.

**Comment by BrandonPotter** [comment]
The new package for this should be out now which includes the TcpClient as a property on the Message object. Let me know if that works!

**Comment by WopsVSV** [comment]
Works like a charm. Thank you!
